### ISSUE TITLE
Weaviate Backend: Create objects in batch instead of one at a time

### ISSUE THREAD

**Issue by StefanBogdan** [jina-ai/docarray#105]
The current setup creates objects sequentially by calling the method [_setitem](https://github.com/jina-ai/docarray/blob/main/docarray/array/storage/weaviate/getsetdel.py#L38-L40), which also checks if objects exists. This code flow is good when the creation requests to the backend are asynchronous, and are not waiting for each object individually to be created. Since the current version of the python client ([v3.3.0](https://weaviate-python-client.readthedocs.io/en/v3.3.0/index.html)) does not allow asynchronous calls, we can achieve it by creatinf objects in [batches](https://weaviate-python-client.readthedocs.io/en/v3.3.0/weaviate.batch.html).

The draw back of creating objects sequentially is that every time we make a request to create the object we wait until Weaviate Server creates the objects and sends back a response. While we wait for the response we could actually send more requests to weaviate to create objects, since objects do not depends on each over (I assume the don't). This can be achieved by collecting objects in a batch and then send them to Weaviate server in one go. This workflow will reduce the waiting time of the main python thread.

Another thing to notice is that creating objects in batch will replace the object/s if the UUID already exists, this means that this  [_setitem](https://github.com/jina-ai/docarray/blob/main/docarray/array/storage/weaviate/getsetdel.py#L38-L40) can be reduced to one line and one batch request.

**Comment by winstonww** [comment]
Hi @StefanBogdan , thank you for the suggestions. Currently we did apply batch update with the `extend` method, but did not realize the `batch`'s `add_data_object` API also does replace/update. As for `_setitem`, it was done this way because the ID field of a document may change. This behavior however is now superseded by `_change_doc_id`.  That said, when performing batch set/update, I think it may still be possible that users update the IDs of some documents. One way I can think of to maybe address this is a two-pass approach (one pass to batch add/update, one pass to batch delete docs with old IDs)? Is this something feasible/something you have in mind?Also we wonder if Weaviate is planning to add async support to the python client? Thanks.

**Comment by StefanBogdan** [comment]
> Also we wonder if Weaviate is planning to add async support to the python client? Thanks.
Yes. This is the main feature for the next release.
