### ISSUE TITLE
Insufficient Weaviate Documentation

### ISSUE THREAD

**Issue by jonathan-rowley** [jina-ai/docarray#329]
I have been trying to use Weaviate as the backend for DocArray but there is very little documentation.

These are the docs i found:
![image](https://user-images.githubusercontent.com/50716090/167009145-3c867063-02c7-4161-a611-4ca416cd8e0d.png)

https://docarray.jina.ai/api/docarray.array.storage.weaviate.backend/?utm_source=docarray
https://docarray.jina.ai/api/docarray.array.storage.weaviate.find/?utm_source=docarray
https://docarray.jina.ai/api/docarray.array.storage.weaviate.getsetdel/?utm_source=docarray
https://docarray.jina.ai/api/docarray.array.storage.weaviate.seqlike/?utm_source=docarray

I have figure out how to upload a DocArray. 

I have figured out how to upload a DocArray with Chunked Documents

I have figured out how to perform a search on Root level Documents

I have figured out how to set Parameter on upload but it is not returned on a search.

I have not figured out how to perform a search on Child (Chunk) level Documents

I have not figured out how to perform a Match

I have not figured out how to perform a Delete function

I have not found out how to perform an update function

Is there a way I can get some help?

**Comment by jonathan-rowley** [comment]
[search.zip](https://github.com/jina-ai/docarray/files/8635501/search.zip)

I have attached a test case of what I am playing with. 

there is a file called install.txt that tells you how i have things set up.

**Comment by alaeddine-13** [comment]
Hello, @jonathan-rowley , thanks for reaching out.
Our Documentation specifies that a DocumentArray with a storage backend (like weaviate), **behaves the same** and **offers the same API** as a regular, in-memory DocumentArray:
[Document Store Section](https://docarray.jina.ai/advanced/document-store/?utm_source=docarray)
Therefore, if you're looking for general features, you can simply jump to [the DocumentArray features in our documentation](https://docarray.jina.ai/fundamentals/documentarray/?utm_source=docarray)

Now, regarding your issues:

- I have not figured out how to perform a search on Child (Chunk) level Documents: efficient search on chunks is not supported, although you can do `da['@c'].find(query)`, it's not efficient because it will traverse all chunks and load them in memory. If you're aiming for scale, consider indexing the chunks in a separate index in Weaviate

- I have not figured out how to perform a Match: use the method `match` like any DocumentArray

- I have not figured out how to perform a Delete function: usw `del` like any DocumentArray

- I have not found out how to perform an update function: use the selector `da[doc.id] = new_doc` like any DocumentArray

I hope this helps you with your issues

**Comment by alaeddine-13** [comment]
I'm assuming my comments solved your issues, feel free to reach out if you have further inqueries

**Comment by jonathan-rowley** [comment]
@alaeddine-13, I am sorry for my late response. My network was hit by lightning and I have been trying to get everything back online. The surge fried my motherboard through my surge protector. If I can recover everything from my Hard Drive I will post screenshots of why some of your responses did not work in my case. Thank you for your reply and I hope to give you more info if I can recover.
