### ISSUE TITLE
Problem with scores, evaluations and serializations

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/docarray#45]
I have found a weird problem, look at this behavior:

```python
from docarray import Document, DocumentArray
d = Document()
d.evaluations['cosine'] = 10
d.to_protobuf()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joan/.local/lib/python3.7/site-packages/docarray/document/mixins/protobuf.py", line 18, in to_protobuf
    return flush_proto(self)
  File "/home/joan/.local/lib/python3.7/site-packages/docarray/proto/io/__init__.py", line 55, in flush_proto
    for ff in vv.non_empty_fields:
AttributeError: ('Field `evaluations` is problematic', "'int' object has no attribute 'non_empty_fields'")
```
```python
from docarray import Document, DocumentArray
d2 = Document()
d2.evaluations['cosine'].value = 10
d2.to_protobuf()
evaluations {
  key: "cosine"
  value {
    value: 10.0
  }
}

```

**Comment by hanxiao** [comment]
it is not so weird, your first usage is wrong as it doesn't fit to the `Document` schema, that's it. 

There is no such sugar syntax implemented anymore.

**Comment by hanxiao** [comment]
I would also be against of adding magic getter & setter as in Jina 2.x.

Big background is docarray is now completely Python native, protobuf is just a "plugin". So static typing is not a thing anymore.

Under this big background, the logic is the following: if one wants to enjoy the freedom and convenience of `d.evaluations['cosine'] = 10`. Sure, no problem. One can even assign it to a string, list, dict, dict of dict, np.float or whatever. **As long as you are not serializing it and send away, you are fine with all crazy types.**

But if you serialize it and send it away, then we enforce you to assign the field formally according to the schema(, or maybe you want to write it formally from the beginning). Because only under the same schema, other services can understand you.

**Comment by JoanFM** [comment]
I would be okey with no magic I would just make it fail.

**Comment by JoanFM** [comment]
Also I have seen some more weirdiness that I will try to investigate tomorrow when updating core

**Comment by hanxiao** [comment]
>  I would just make it fail.

It is unnatural in Python tho. What you are suggesting is basically adding static typing back. This contradicts the new design:

> Big background is docarray is now completely Python native, protobuf is just a "plugin". So static typing is not a thing anymore.


Think about it:

```python
class Man:
   age: int
```

And nothing prevents user to say
```python
Man().age = '18 years old'
```

**Comment by JoanFM** [comment]
Yes u are right. I will open an issue to add a section if that's okey
